# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53a240c468d73d38543228ab0c74c63dcb9e07aef7b1d3f35fda569921344adb9450af9e5a69e50faaaccf1fa58d3ea885729b4bb6de4ad019cf38a4c6c1f2f6

test:
  secret_key_base: e1e195434272887c3ba1f4208df29b79fe731cddb8cb7285fb6778be2b2a418d57824a5359600b49bcad6b1a87ccc5af5e304eab64f5c1b3671727beae224fba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
